# Découverte de Numpy

## Introduction à Numpy

In [ ]:
list_of_list = [["Paris",75], ["Lyon", 69]]

In [1]:
list = [1, "film", 3]

In [2]:
list.append("série")
print(list)

[1, 'film', 3, 'série']


## Les tableaux avec Numpy

ndarray

In [4]:
import numpy as np

In [5]:
vector = np.array([3, 4, 17, 65])

In [6]:
print(vector)

[ 3  4 17 65]


In [7]:
matrix = np.array([[2, 5, 15], [20, 50, 30], [34, 99, 45]])

In [9]:
print(matrix)

[[ 2  5 15]
 [20 50 30]
 [34 99 45]]


### Exercice

In [18]:
import numpy as np 
vector = np.array([10, 20, 30])
matrix = np.array([[50, 10, 15], [20, 25, 30], [35, 40, 45]])

In [19]:
print(vector)

[10 20 30]


In [20]:
print(matrix)

[[50 10 15]
 [20 25 30]
 [35 40 45]]


## Taille d'un tableau

In [21]:
np.array(["1986", "Western Pacific", "Viet Nam", "Wine", "0"])

array(['1986', 'Western Pacific', 'Viet Nam', 'Wine', '0'], dtype='<U15')

In [30]:
np.array([["1986", "Western Pacific", "Viet Nam", "Wine", "0"], ["1986", "Americas", "Uruguay", "Other", "0.5"], ["1985", "Africa", "Ghana", "Wine", "1.62"]])

array([['1986', 'Western Pacific', 'Viet Nam', 'Wine', '0'],
       ['1986', 'Americas', 'Uruguay', 'Other', '0.5'],
       ['1985', 'Africa', 'Ghana', 'Wine', '1.62']], dtype='<U15')

ndarray.shape

In [32]:
vector = np.array([1, 2, 3, 4])
print(vector.shape)

(4,)


In [35]:
matrix = np.array([[5, 10, 15], [20, 25, 30]])
print(matrix.shape)

(2, 3)


### Exercice

In [36]:
import numpy as np 
vector = np.array([10, 20, 30])
matrix = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

In [37]:
print(vector.shape)

(3,)


In [38]:
print(matrix.shape)

(3, 3)


## Lire un dataset avec Numpy

In [39]:
# fonction numpy pour lire un dataset: numpy.genfromtxt()

In [ ]:
import numpy as np
test = np.genfromtxt("data.csv"), delimiter=",")

### Exercice

In [41]:
# Lire un dataset numpy.genfromtxt()

In [47]:
import numpy as np

world_alcohol = np.genfromtxt("world_alcohol.csv", delimiter=",")
print(type(world_alcohol))

<class 'numpy.ndarray'>


## Les types de données avec Numpy

In [48]:
# bool --> True ou False

In [49]:
# int --> integer

In [50]:
# float 

In [51]:
# string 

In [52]:
numbers = np.array([1, 2, 3, 4])

In [53]:
numbers.dtype

dtype('int64')

### Exercice

In [62]:
#world_alcohol_dtype = world_alcohol.dtype
#print(world_alcohol_dtype)

In [63]:
#float64

## Afficher les données correctement 

In [69]:
world_alcohol = np.genfromtxt("world_alcohol.csv", delimiter=",", dtype="U75", skip_header=1)
world_alcohol

array([['1986', 'Western Pacific', 'Viet Nam', 'Wine', '0'],
       ['1986', 'Americas', 'Uruguay', 'Other', '0.5'],
       ['1985', 'Africa', "Cte d'Ivoire", 'Wine', '1.62'],
       ...,
       ['1986', 'Europe', 'Switzerland', 'Spirits', '2.54'],
       ['1987', 'Western Pacific', 'Papua New Guinea', 'Other', '0'],
       ['1986', 'Africa', 'Swaziland', 'Other', '5.15']], dtype='<U75')

## Extraire une valeur depuis un tableau Numpy

In [70]:
vector = np.array([1, 2, 3, 4])
print(vector[0])

1


In [71]:
list_of_list = [[5, 10, 15], [20, 25, 30]]

In [72]:
first_row = list_of_list[0]

In [73]:
first_row[2]

15

In [74]:
# Autre méthode

In [77]:
list_of_list[0][2]

15

In [78]:
matrix = np.array([[5, 10, 15], [20, 25, 30]])

In [79]:
matrix[1,2]

30

### Exercice 

In [80]:
ivoire_1985 = world_alcohol[2,4]
print(ivoire_1985)

1.62


In [82]:
second_country = world_alcohol[1,2]
print(second_country)

Uruguay


## Extraire un vecteur de valeurs depuis un tableau Numpy

In [83]:
vector = np.array ([1, 2, 3, 4, 5])

In [84]:
vector[0:3]

array([1, 2, 3])

In [85]:
matrix = np.array ([[1, 2, 3], [16, 15, 20], [25, 26, 27]])

In [86]:
matrix

array([[ 1,  2,  3],
       [16, 15, 20],
       [25, 26, 27]])

In [88]:
matrix[:,1]

array([ 2, 15, 26])

In [93]:
# Explication matrix 
# : toutes les lignes 
# ,1 deuxiéme valeur des colonnes 

In [91]:
matrix[2,:]

array([25, 26, 27])

In [94]:
# 1:3 = commence de 15 jusqu'a 26
# ,1 = colonne du milieu

In [92]:
matrix[1:3,1]

array([15, 26])

### Exercice

In [98]:
countries = world_alcohol[:,2]
print(countries)

['Viet Nam' 'Uruguay' "Cte d'Ivoire" ... 'Switzerland' 'Papua New Guinea'
 'Swaziland']


In [99]:
alcohol_consumption = world_alcohol[:,4]
print(alcohol_consumption)

['0' '0.5' '1.62' ... '2.54' '0' '5.15']


## Extraire un tableau de valeurs depuis un tableau Numpy

In [100]:
matrix

array([[ 1,  2,  3],
       [16, 15, 20],
       [25, 26, 27]])

In [108]:
# :,0:2 = Toutes les valeurs des deux premieres colonnes

In [109]:
matrix[:,0:2]

array([[ 1,  2],
       [16, 15],
       [25, 26]])

In [110]:
# 1:3,: = Toutes les valeurs des deux premieres lignes

In [107]:
matrix[1:3,:]

array([[16, 15, 20],
       [25, 26, 27]])

In [110]:
# [1:3,0:2]= Les deux valeurs des deux dernières lignes et Les deux valeurs des deux premières colonnes

In [112]:
matrix[1:3,0:2]

array([[16, 15],
       [25, 26]])

### Exercice

In [114]:
first_two_columns = world_alcohol[:,0:2]
print(first_two_columns)

[['1986' 'Western Pacific']
 ['1986' 'Americas']
 ['1985' 'Africa']
 ...
 ['1986' 'Europe']
 ['1987' 'Western Pacific']
 ['1986' 'Africa']]


In [122]:
first_ten_years = world_alcohol[0:10,0:1]
print(first_ten_years)

[['1986']
 ['1986']
 ['1985']
 ['1986']
 ['1987']
 ['1987']
 ['1987']
 ['1985']
 ['1986']
 ['1984']]


In [118]:
first_ten_rows = world_alcohol[0:10,:]
print(first_ten_rows)

[['1986' 'Western Pacific' 'Viet Nam' 'Wine' '0']
 ['1986' 'Americas' 'Uruguay' 'Other' '0.5']
 ['1985' 'Africa' "Cte d'Ivoire" 'Wine' '1.62']
 ['1986' 'Americas' 'Colombia' 'Beer' '4.27']
 ['1987' 'Americas' 'Saint Kitts and Nevis' 'Beer' '1.98']
 ['1987' 'Americas' 'Guatemala' 'Other' '0']
 ['1987' 'Africa' 'Mauritius' 'Wine' '0.13']
 ['1985' 'Africa' 'Angola' 'Spirits' '0.39']
 ['1986' 'Americas' 'Antigua and Barbuda' 'Spirits' '1.55']
 ['1984' 'Africa' 'Nigeria' 'Other' '6.1']]


In [120]:
first_twenty_regions = world_alcohol[0:20,1:3]
print(first_twenty_regions)

[['Western Pacific' 'Viet Nam']
 ['Americas' 'Uruguay']
 ['Africa' "Cte d'Ivoire"]
 ['Americas' 'Colombia']
 ['Americas' 'Saint Kitts and Nevis']
 ['Americas' 'Guatemala']
 ['Africa' 'Mauritius']
 ['Africa' 'Angola']
 ['Americas' 'Antigua and Barbuda']
 ['Africa' 'Nigeria']
 ['Africa' 'Botswana']
 ['Americas' 'Guatemala']
 ['Western Pacific' "Lao People's Democratic Republic"]
 ['Eastern Mediterranean' 'Afghanistan']
 ['Western Pacific' 'Viet Nam']
 ['Africa' 'Guinea-Bissau']
 ['Americas' 'Costa Rica']
 ['Africa' 'Seychelles']
 ['Europe' 'Norway']
 ['Africa' 'Kenya']]
