# Analyse de données avec Numpy

## Objectif

In [3]:
import numpy as np 

world_alcohol = np.genfromtxt("world_alcohol.csv", delimiter=",", dtype="U75", skip_header=1)
world_alcohol

array([['1986', 'Western Pacific', 'Viet Nam', 'Wine', '0'],
       ['1986', 'Americas', 'Uruguay', 'Other', '0.5'],
       ['1985', 'Africa', "Cte d'Ivoire", 'Wine', '1.62'],
       ...,
       ['1986', 'Europe', 'Switzerland', 'Spirits', '2.54'],
       ['1987', 'Western Pacific', 'Papua New Guinea', 'Other', '0'],
       ['1986', 'Africa', 'Swaziland', 'Other', '5.15']], dtype='<U75')

## Effectuer des comparaisons

In [4]:
vector = np.array([1, 2, 3, 4, 5])

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.


In [6]:
vector == 5

array([False, False, False, False,  True])

In [11]:
matrix = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [9]:
matrix == 25

array([[False, False, False],
       [False,  True, False],
       [False, False, False]])

### Exercice

In [19]:
countries_canada = (world_alcohol[:,2] == "Canada")

In [ ]:
years_1984 = (world_alcohol[:,0] == "1984")

## Sélectionner des éléments

In [ ]:
# Permettre de sélectionner des éléments 

In [24]:
vector = np.array([1, 2, 3, 4])
equal_to_ten = (vector == 10)
print(vector[equal_to_ten])

[]


In [26]:
vector = np.array([1, 2, 3, 4])
equal_to_two = (vector == 2)
print(vector[equal_to_two])

[2]


In [27]:
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [29]:
second_colomn_25 = (matrix[:,1] == 25)
print(matrix[second_colomn_25])

[[20 25 30]]


### Exercice

In [30]:
country_is_algeria = world_alcohol[:,2] == "Algeria"
country_algeria = world_alcohol[country_is_algeria]
print(country_algeria)

[['1984' 'Africa' 'Algeria' 'Spirits' '0.01']
 ['1987' 'Africa' 'Algeria' 'Beer' '0.17']
 ['1987' 'Africa' 'Algeria' 'Spirits' '0.01']
 ['1986' 'Africa' 'Algeria' 'Wine' '0.1']
 ['1984' 'Africa' 'Algeria' 'Other' '0']
 ['1989' 'Africa' 'Algeria' 'Beer' '0.16']
 ['1989' 'Africa' 'Algeria' 'Spirits' '0.01']
 ['1989' 'Africa' 'Algeria' 'Wine' '0.23']
 ['1986' 'Africa' 'Algeria' 'Spirits' '0.01']
 ['1984' 'Africa' 'Algeria' 'Wine' '0.12']
 ['1985' 'Africa' 'Algeria' 'Beer' '0.19']
 ['1985' 'Africa' 'Algeria' 'Other' '0']
 ['1986' 'Africa' 'Algeria' 'Beer' '0.18']
 ['1985' 'Africa' 'Algeria' 'Wine' '0.11']
 ['1986' 'Africa' 'Algeria' 'Other' '0']
 ['1989' 'Africa' 'Algeria' 'Other' '0']
 ['1987' 'Africa' 'Algeria' 'Other' '0']
 ['1984' 'Africa' 'Algeria' 'Beer' '0.2']
 ['1985' 'Africa' 'Algeria' 'Spirits' '0.01']
 ['1987' 'Africa' 'Algeria' 'Wine' '0.1']]


In [31]:
# Faire le même travail pour récupérer toutes les lignes correspondantes à l'année "1984". Assigner le résultat à la variable years_1984.

In [34]:
year_is_1984 = world_alcohol[:,0] == "1984"
years_1984 = world_alcohol[year_is_1984]
print(years_1984)

[['1984' 'Africa' 'Nigeria' 'Other' '6.1']
 ['1984' 'Eastern Mediterranean' 'Afghanistan' 'Other' '0']
 ['1984' 'Americas' 'Costa Rica' 'Wine' '0.06']
 ...
 ['1984' 'Europe' 'Latvia' 'Spirits' '7.5']
 ['1984' 'Africa' 'Angola' 'Wine' '0.57']
 ['1984' 'Africa' 'Central African Republic' 'Wine' '0.46']]


In [35]:
# On peut condenser sur la même ligne le code

In [36]:
years_1984 = world_alcohol[world_alcohol[:,0] == "1984"]
print(years_1984)

[['1984' 'Africa' 'Nigeria' 'Other' '6.1']
 ['1984' 'Eastern Mediterranean' 'Afghanistan' 'Other' '0']
 ['1984' 'Americas' 'Costa Rica' 'Wine' '0.06']
 ...
 ['1984' 'Europe' 'Latvia' 'Spirits' '7.5']
 ['1984' 'Africa' 'Angola' 'Wine' '0.57']
 ['1984' 'Africa' 'Central African Republic' 'Wine' '0.46']]


## Effectuer des comparaisons avec plusieurs conditions

In [37]:
vector

array([1, 2, 3, 4])

In [41]:
equal_to_ten_and_five = (vector == 2) | (vector == 1)
print(equal_to_ten_and_five)

[ True  True False False]


### Exercice

In [45]:
is_algeria_and_1986 = (world_alcohol[:,2] == "Algeria") & (world_alcohol[:,0] == "1986")
rows_with_algeria_and_1986 = world_alcohol[is_algeria_and_1986]
print(rows_with_algeria_and_1986)

[['1986' 'Africa' 'Algeria' 'Wine' '0.1']
 ['1986' 'Africa' 'Algeria' 'Spirits' '0.01']
 ['1986' 'Africa' 'Algeria' 'Beer' '0.18']
 ['1986' 'Africa' 'Algeria' 'Other' '0']]


## Remplacer des valeurs dans un tableau Numpy

In [46]:
vector

array([1, 2, 3, 4])

In [47]:
equal_to_two_and_one = (vector == 2) | (vector == 1)
print(equal_to_two_and_one)

[ True  True False False]


In [48]:
vector[equal_to_two_and_one] = 50
print(vector)

[50 50  3  4]


In [65]:
matrix

array([[ 5, 10, 15],
       [99, 10, 99],
       [35, 40, 45]])

In [66]:
second_colom_10 = matrix[:,1] == 10
print(second_colom_10)

[ True  True False]


In [67]:
matrix[second_colom_10, 1] = 30
print(matrix)

[[ 5 30 15]
 [99 30 99]
 [35 40 45]]


### Exercice

In [68]:
# Création d'une copy

In [69]:
world_alcohol_2 = world_alcohol.copy()

In [72]:
# Remplacer toutes les années "1986" de la première colonne de world_alcohol_2 par "2018"

In [73]:
world_alcohol_2[:,0][world_alcohol_2[:,0] == "1986"] = "2018"

In [74]:
# Remplacer tous les alcools "Wine" de la 4e colonne de world_alcohol_2 par "Beer"

In [75]:
world_alcohol_2[:,3][world_alcohol_2[:,3] == "Wine"] = "Beer"

## Remplacer les chaines de caractères vides

In [76]:
is_value_empty = world_alcohol[:,4] == ''
world_alcohol[is_value_empty, 4] = 0

## Convertir des types de données

In [77]:
# astype()

In [78]:
vector = np.array(["1", "2", "3"])

In [79]:
vector = vector.astype(float)

In [80]:
vector

array([1., 2., 3.])

### Exercice

In [81]:
alcohol_consumption = world_alcohol[:,4]
alcohol_consumption = alcohol_consumption.astype(float)
print(alcohol_consumption)

[0.   0.5  1.62 ... 2.54 0.   5.15]


## Réaliser des calculs mathématique avec Numpy

In [82]:
# sum()
# mean()
# max()

In [83]:
vector = np.array([5, 10, 15, 20])

In [84]:
vector.sum()

50

In [86]:
# Mean = 50 (Somme) / 4 (nombre d'éléments)

In [85]:
vector.mean()

12.5

In [ ]:
# Le variable maximum

In [87]:
vector.max()

20

In [88]:
matrix = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

In [89]:
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [91]:
# la somme des lignes

In [90]:
matrix.sum(axis=1)

array([ 30,  75, 120])

In [ ]:
# La somme des colonnes

In [92]:
matrix.sum(axis=0)

array([60, 75, 90])

### Exercice

In [94]:
total_alcohol = alcohol_consumption.sum()
print(total_alcohol)

3908.96


In [95]:
average_alcohol = alcohol_consumption.mean()
print(average_alcohol)

1.2001719373656738


## Calculer la consommation totale annuelle par habitant pour un pays donné

In [98]:
print(world_alcohol[world_alcohol[:,2] == "Canada"])

[['1984' 'Americas' 'Canada' 'Spirits' '3.35']
 ['1989' 'Americas' 'Canada' 'Wine' '1.27']
 ['1984' 'Americas' 'Canada' 'Beer' '5']
 ['1985' 'Americas' 'Canada' 'Beer' '4.94']
 ['1987' 'Americas' 'Canada' 'Wine' '1.3']
 ['1987' 'Americas' 'Canada' 'Beer' '4.83']
 ['1986' 'Americas' 'Canada' 'Other' '0']
 ['1986' 'Americas' 'Canada' 'Spirits' '3.11']
 ['1985' 'Americas' 'Canada' 'Spirits' '3.21']
 ['1985' 'Americas' 'Canada' 'Other' '0']
 ['1986' 'Americas' 'Canada' 'Beer' '4.87']
 ['1984' 'Americas' 'Canada' 'Wine' '1.24']
 ['1989' 'Americas' 'Canada' 'Spirits' '2.91']
 ['1984' 'Americas' 'Canada' 'Other' '0']
 ['1985' 'Americas' 'Canada' 'Wine' '1.29']
 ['1987' 'Americas' 'Canada' 'Spirits' '2.99']
 ['1989' 'Americas' 'Canada' 'Beer' '4.82']
 ['1989' 'Americas' 'Canada' 'Other' '0']
 ['1986' 'Americas' 'Canada' 'Wine' '1.33']
 ['1987' 'Americas' 'Canada' 'Other' '0']]


### Exercice

In [100]:
is_canada_1986 = (world_alcohol[:,2] == "Canada") & (world_alcohol[:,0] == "1986")
canada_1986 = world_alcohol[is_canada_1986]
print(canada_1986)

[['1986' 'Americas' 'Canada' 'Other' '0']
 ['1986' 'Americas' 'Canada' 'Spirits' '3.11']
 ['1986' 'Americas' 'Canada' 'Beer' '4.87']
 ['1986' 'Americas' 'Canada' 'Wine' '1.33']]


In [103]:
canada_alcohol = canada_1986[:,4]
print(canada_alcohol)

['0' '3.11' '4.87' '1.33']


In [105]:
canada_alcohol = canada_alcohol.astype(float)
print(canada_alcohol)

[0.   3.11 4.87 1.33]


In [109]:
total_canadian_drinking = canada_alcohol.sum()
print(total_canadian_drinking)

9.31


## Calculer la consommation pour chaque pays

In [111]:
totals = {}

is_year = world_alcohol[:,0] == "1989"
year = world_alcohol[is_year,:]
countries = world_alcohol[:,2]

for country in countries:
    is_country = year[:,2] == country
    country_consumption =  year[is_country,:]
    alcohol_column = country_consumption[:,4]
    is_empty = alcohol_column == ''
    alcohol_column[is_empty] = 0
    alcohol_column = alcohol_column.astype(float)
    totals[country] = alcohol_column.sum()

print(totals)

{'Viet Nam': 0.16, 'Uruguay': 7.4399999999999995, "Cte d'Ivoire": 2.2, 'Colombia': 6.960000000000001, 'Saint Kitts and Nevis': 4.65, 'Guatemala': 2.47, 'Mauritius': 3.54, 'Angola': 2.28, 'Antigua and Barbuda': 4.69, 'Nigeria': 6.74, 'Botswana': 4.63, "Lao People's Democratic Republic": 5.95, 'Afghanistan': 0.0, 'Guinea-Bissau': 2.67, 'Costa Rica': 5.3999999999999995, 'Seychelles': 3.3000000000000003, 'Norway': 5.08, 'Kenya': 2.82, 'Myanmar': 0.16, 'Romania': 8.41, 'Turkey': 0.72, 'Comoros': 0.10999999999999999, 'Tunisia': 0.95, 'United Kingdom of Great Britain and Northern Ireland': 9.99, 'Bahrain': 4.89, 'Italy': 10.899999999999999, 'Sierra Leone': 4.380000000000001, 'Micronesia (Federated States of)': 0.0, 'Mauritania': 0.02, 'Russian Federation': 5.35, 'Egypt': 0.42000000000000004, 'Sweden': 7.47, 'Qatar': 1.4500000000000002, 'Burkina Faso': 3.99, 'Austria': 13.9, 'Czech Republic': 13.009999999999998, 'Ukraine': 5.32, 'China': 3.33, 'Lithuania': 0.0, 'Zimbabwe': 4.92, 'Trinidad and 

## Trouver le pays qui consomme le plus d'alcool

In [112]:
highest_value = 0
highest_key = None

for country in totals: 
    consumption = totals[country]
    if highest_value < consumption: 
        highest_value = consumption
        highest_key = country

print(highest_key)

Hungary


In [113]:
print(highest_value)

16.29
